# Generated by Django 5.2.14 on 2026-05-11 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_category', models.CharField(default='', max_length=200)),
                ('label', models.CharField(max_length=400)),
                ('amount_cents', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_at_epoch_millis', models.BigIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('quantity', models.FloatField(default=0.0)),
                ('unit', models.CharField(default='kg', max_length=64)),
                ('low_stock_threshold', models.FloatField(default=0.0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('category', models.CharField(max_length=200)),
                ('price_cents', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('custom_photo_url', models.CharField(blank=True, default='', max_length=2000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('category', 'name'),
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(default='Staff', max_length=200)),
                ('on_shift', models.BooleanField(default=False)),
                ('salary_cents', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VenueOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='OPEN', max_length=32)),
                ('created_at_epoch_millis', models.BigIntegerField(default=0)),
                ('total_cents', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at_epoch_millis',),
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price_cents', models.IntegerField()),
                ('kitchen_status', models.CharField(default='QUEUED', max_length=32)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='venue.venueorder')),
            ],
        ),
        migrations.CreateModel(
            name='VenueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(default='My Restaurant', max_length=400)),
                ('tax_percent', models.FloatField(default=5.0)),
                ('service_charge_percent', models.FloatField(default=0.0)),
                ('qr_menu_token', models.CharField(blank=True, default='', max_length=200)),
                ('menu_categories', models.TextField(blank=True, default='')),
                ('expense_categories', models.TextField(blank=True, default='')),
                ('modules_json', models.TextField(blank=True, default='{}')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venue_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VenueTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('section', models.CharField(default='Main', max_length=200)),
                ('status', models.CharField(default='FREE', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_tables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('section', 'label'),
            },
        ),
        migrations.AddField(
            model_name='venueorder',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='venue.venuetable'),
        ),
        migrations.CreateModel(
            name='StaffAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_start_epoch_millis', models.BigIntegerField()),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='venue.staffmember')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('staff', 'day_start_epoch_millis'), name='venue_staffabsence_staff_day')],
            },
        ),
    ]
