# Generated by Django 5.2.14 on 2026-05-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_tablereservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='party_size',
            field=models.PositiveIntegerField(default=2, verbose_name='Number of guests'),
        ),
    ]
